source 'https://rubygems.org'
ruby '3.2.2' # Example version, change to yours

gem 'rails', '~> 7.1.3'
gem 'sqlite3', '~> 1.4'
gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'active_storage_validations'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails', '~> 6.1.0'
  gem 'factory_bot_rails'
end
